@echo off
REM **Version:** v0.92.0
REM Launch Claude Code (bypass permissions mode)
REM Generated by IDPF Framework installer

REM Check for --accepted flag
if "%~1"=="--accepted" (
  claude --permission-mode "bypassPermissions" "Start"
  exit /b %errorlevel%
)

REM Show WARNING: Bypass Mode warning and prompt
echo.
echo =========================================
echo   WARNING: Bypass Mode
echo =========================================
echo.
echo Enabling bypass mode allows Claude to execute commands without the
echo standard safety prompts and permission checks. This means:
echo.
echo   - Commands will run without interactive confirmation
echo   - File modifications, deletions, and system changes may occur without review
echo   - Network requests and external tool invocations will proceed automatically
echo.
echo Only enable bypass mode if you understand the risks and trust the
echo commands being executed in this project.
echo.
set /p "RESPONSE=Do you accept and wish to continue? (y/N) "

if /i "%RESPONSE%"=="y" goto :launch
if /i "%RESPONSE%"=="yes" goto :launch

echo Bypass mode declined. Exiting.
exit /b 0

:launch
claude --permission-mode "bypassPermissions" "Start"
exit /b %errorlevel%
