// Rubrical Works (c) 2026
/**
 * @framework-script 0.101.0
 * @description Classify files and commits by deployment scope (deployed vs dev-only).
 * Uses minimize-config.json rules, deployment chain awareness, and known path patterns.
 * Used by generate-changelog.js to separate user-facing from internal changes.
 * @checksum sha256:placeholder
 */

const fs = require('fs');
const path = require('path');

// --- Load minimize-config.json ---

let _config = null;

const EMPTY_CONFIG = { excludedCommands: [], excludedDirectories: [], includedDirectories: [] };

/**
 * Load minimize-config.json, recording whether it was actually found (#2602).
 *
 * The `loaded` flag is the whole point. This file lives under
 * `.claude/scripts/framework/`, which is dev-repo-only and never deployed, so in
 * a consuming project the read always fails and the empty-array substitution
 * used to be indistinguishable from a real config with nothing in it — every
 * path then fell through to a confident `dev-only`.
 *
 * @param {string} [configPath] - override; also bypasses the module cache, so
 *   tests can point at a fixture without poisoning subsequent calls
 * @returns {object} the config, plus a non-enumerable `loaded` boolean
 */
function loadConfig(configPath) {
    if (!configPath && _config) return _config;

    const resolved = configPath || path.resolve(__dirname, '../../framework/minimize-config.json');
    let result;
    try {
        result = { ...JSON.parse(fs.readFileSync(resolved, 'utf8')), loaded: true };
    } catch {
        result = { ...EMPTY_CONFIG, loaded: false };
    }

    if (!configPath) _config = result;
    return result;
}

/**
 * Deployed paths a consuming project declares for itself (#2602).
 *
 * The escape hatch for projects that have no minimize-config.json — which is
 * every project except this one. Read from `framework-config.json`
 * `deployedPaths`: a list of path prefixes that ship.
 *
 * @param {string} [projectRoot] - defaults to the current working directory,
 *   which is the consuming project when a symlinked helper runs inside it
 * @returns {string[]}
 */
function loadDeclaredPaths(projectRoot) {
    const root = projectRoot || process.cwd();
    try {
        const cfg = JSON.parse(fs.readFileSync(path.join(root, 'framework-config.json'), 'utf8'));
        return Array.isArray(cfg.deployedPaths) ? cfg.deployedPaths : [];
    } catch {
        return [];
    }
}

/**
 * Whether the classifier has anything to classify against.
 *
 * False means every answer outside the built-in patterns is a guess, and
 * `classifyFile` returns `'unknown'` rather than pretending otherwise.
 *
 * @param {{configPath?: string, projectRoot?: string}} [options]
 * @returns {boolean}
 */
function hasClassificationBasis(options = {}) {
    const config = loadConfig(options.configPath);
    // An empty deployedPaths array is not a declaration. Treating it as one
    // would quietly restore the confident dev-only this change removed.
    const declared = options.declaredPaths || loadDeclaredPaths(options.projectRoot);
    return Boolean(config.loaded) || declared.length > 0;
}

// --- Dev-only path patterns (not in minimize-config but known dev-only) ---

const DEV_ONLY_PATTERNS = [
    /^tests\//,
    /^\.claude\/rules\//,           // Self-hosted: synced from Reference/ via /fw-minimize-files (preserves FRAMEWORK-ONLY); user projects: generated by PHM hub-setup.ts from pre-stripped Reference/. Never deploys directly.
    /^\.github\//,                  // CI workflows
    /^CLAUDE\.md$/,
    /^\.gh-pmu\.json$/,
    /^framework-config\.json$/,
    /^CHARTER\.md$/,
    /^Skills\/(?!Packaged\/)/,      // Skill source dirs (Packaged/ is deployed)
    /^Inception\//,
    /^Construction\//,
    /^Transition\//,
];

// --- Deployed path patterns (known deployed regardless of minimize-config) ---

const DEPLOYED_PATTERNS = [
    /^\.claude\/scripts\//,         // Symlinked to user projects
    /^\.claude\/hooks\//,           // Symlinked to user projects
    /^\.claude\/metadata\//,        // Symlinked to user projects
    /^Skills\/Packaged\//,          // Skill zip files deployed
    /^framework-manifest\.json$/,   // Deployed as-is
    /^CHANGELOG\.md$/,              // Deployed as-is
    /^LICENSE$/,                    // Deployed as-is
];

/**
 * Classify a single file path as 'deployed', 'dev-only' or 'unknown'.
 *
 * `'unknown'` is returned only when the path matched no built-in pattern AND
 * there was no basis to classify against (#2602) — no minimize-config.json and
 * no project-declared deployedPaths. It is deliberately distinguishable from
 * `'dev-only'`: a consuming project needs to be able to tell "this is internal"
 * from "the classifier did not apply here".
 *
 * @param {string} filePath - Relative file path from repo root
 * @param {{configPath?: string, projectRoot?: string, declaredPaths?: string[]}} [options]
 * @returns {'deployed'|'dev-only'|'unknown'}
 */
function classifyFile(filePath, options = {}) {
    const config = loadConfig(options.configPath);
    const declared = options.declaredPaths || loadDeclaredPaths(options.projectRoot);
    const normalized = filePath.replace(/\\/g, '/');

    // Check excluded commands first (most specific)
    if (config.excludedCommands && config.excludedCommands.includes(normalized)) {
        return 'dev-only';
    }

    // Check dev-only patterns
    for (const pattern of DEV_ONLY_PATTERNS) {
        if (pattern.test(normalized)) return 'dev-only';
    }

    // Check excluded directories
    if (config.excludedDirectories) {
        for (const dir of config.excludedDirectories) {
            if (normalized.startsWith(dir + '/') || normalized === dir) {
                return 'dev-only';
            }
        }
    }

    // Check deployed patterns
    for (const pattern of DEPLOYED_PATTERNS) {
        if (pattern.test(normalized)) return 'deployed';
    }

    // Check included directories (deployed via .min-mirror/)
    if (config.includedDirectories) {
        for (const dir of config.includedDirectories) {
            if (normalized.startsWith(dir + '/') || normalized === dir) {
                return 'deployed';
            }
        }
    }

    // Project-declared deployed paths — the escape hatch for a consuming
    // project, which has no minimize-config.json of its own (#2602).
    for (const dir of declared) {
        const prefix = dir.endsWith('/') ? dir : dir + '/';
        if (normalized.startsWith(prefix) || normalized === dir.replace(/\/$/, '')) {
            return 'deployed';
        }
    }

    // Nothing matched. Whether that means "internal" or "no idea" depends on
    // whether there was anything to match against (#2602).
    if (!config.loaded && declared.length === 0) return 'unknown';

    // Default: dev-only (unknown files are assumed internal)
    return 'dev-only';
}

/**
 * Classify a commit based on its changed files.
 *
 * A commit is 'deployed' if ANY of its files are deployed — unchanged. When
 * none are, it is 'unknown' if any file was unclassifiable, else 'dev-only'
 * (#2602). Deployed still wins outright: one shipped file makes the commit
 * user-facing whatever the rest were.
 *
 * An empty file list stays 'dev-only'. Nothing changed is not the same as
 * nothing classifiable, and reporting the empty case as unknown would flag
 * every merge commit.
 *
 * @param {string[]} files - Array of file paths changed in the commit
 * @param {{configPath?: string, projectRoot?: string, declaredPaths?: string[]}} [options]
 * @returns {'deployed'|'dev-only'|'unknown'}
 */
function classifyCommit(files, options = {}) {
    if (!files || files.length === 0) return 'dev-only';
    const scopes = files.map(f => classifyFile(f, options));
    if (scopes.includes('deployed')) return 'deployed';
    if (scopes.includes('unknown')) return 'unknown';
    return 'dev-only';
}

module.exports = { classifyFile, classifyCommit, hasClassificationBasis };
